language: go
before_script:
  - go get -u github.com/nats-io/gnatsd
  - gnats="$GOPATH/bin/gnatsd"
  - $gnats &
services:
  - redis-server
go:
 - 1.2
 - 1.3
 - 1.4
 - 1.5
 - tip
install: 
    - make deps && make dev-deps
    - cp config.json.tpl config.json
script:
    - make lint
    - make test
